DATABASE_URL: "postgres://postgres:password@localhost:5432/postsdb?sslmode=disable"
PORT: "8080"
JWT_SECRET: "20fbea128cc280c8c64a4d0c876fca49682d39d143e02a46eb3c8859e48c8beb2cfdbd0c11dbad0163e1274d88090b5f051bb0d0884270984043a40de4cb4c73fb53c7c2ed1eaed71578838d365ae35cc45829ee5c1e1ad2f29954e075ced9ac49d9ad839b041c17a195671b510b86593732190a3d0c52906bab5e9b5aa8cb97ad5a4cc09e9d89329520a6b31dde2d7fc0fcbb05e0695710d0700b3a2ccad9ad01a1de3b4a1411f754fd275e1ad205e7a726f3ccb63c42efaf9a48bb214144a413a438d190fdd74947865338deb362f893a332c0173ed0b6f34c1c4c3412a6416bb29779b19a8f9fc44152cd74474fd624af15ffd0247682190e750d80471ce8"
ACCESS_KEY: "M8Kjf3vpymphKULcLzJn"
SECRET_KEY: "Un1Xkp29Sq8TOYZixlurgBpUwyqhUGlLtAadpkqG"
MINIO_BUCKET: "crudexample"

REDIS_ADDR: "localhost:6379"
REDIS_PASS: ""

KAFKA_BROKERS:
  - "localhost:9092"
KAFKA_TOPIC: "likes-events"